name: SpringBoot CI with Maven - PROD

on:
  push:
    branches: [ "PROD" ]
  pull_request:
    branches: [ "PROD" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven (PROD)
        run: mvn clean install -Pprod -e
      - name: Run Tests
        run: mvn verify
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image (PROD)
        with:
          image: assiya24/springboot-mysql-docker-prod
          tags: prod
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
